# Generated by Django 5.2.5 on 2025-09-15 15:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0006_remove_product_free_delivery_from_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Receiver's full name", max_length=150),
                ),
                ("address", models.TextField(help_text="Delivery address")),
                (
                    "city",
                    models.CharField(help_text="City for delivery", max_length=100),
                ),
                (
                    "pin_code",
                    models.CharField(help_text="Postal or ZIP code", max_length=10),
                ),
                (
                    "phone",
                    models.CharField(help_text="Contact phone number", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Order status",
                        max_length=20,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost of the order",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Order creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last updated date"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who placed the order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantity of this product",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price at the time of purchase",
                        max_digits=10,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="oders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product being purchased",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cod", "Cash on Delivery"),
                            ("card", "Credit/Debit Card"),
                            ("upi", "UPI"),
                        ],
                        help_text="Payment method used",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount paid", max_digits=10
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of payment"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional transaction ID for online payments",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Associated order for this payment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="oders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="oders_order_status_51432a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order", "product"], name="oders_order_order_i_278127_idx"
            ),
        ),
    ]
