# Generated by Django 5.2.5 on 2025-09-26 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code customers will use (e.g., SAVE10).",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        default="percentage",
                        help_text="Select the type of discount.",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Value of the discount (e.g., 10 for 10% or ₹500 fixed).",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Minimum order total required to apply this coupon.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        help_text="Start date and time when this coupon becomes active."
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        help_text="Expiry date and time for this coupon."
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable or disable this coupon globally.",
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum times this coupon can be used (leave blank for unlimited).",
                        null=True,
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this coupon has been used.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when this coupon was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this coupon was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "ordering": ["-valid_from"],
                "indexes": [
                    models.Index(fields=["code"], name="coupons_cou_code_3bf721_idx"),
                    models.Index(
                        fields=["valid_from", "valid_to"],
                        name="coupons_cou_valid_f_cf442c_idx",
                    ),
                ],
            },
        ),
    ]
