# Generated by Django 5.2.5 on 2025-09-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="pendinguser",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="pending_profiles/"
            ),
        ),
    ]
