# Generated by Django 5.2.5 on 2025-09-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_pendinguser_mobile_no_pendinguser_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendinguser",
            name="mobile_no",
        ),
        migrations.RemoveField(
            model_name="pendinguser",
            name="profile_pic",
        ),
    ]
