# Generated by Django 5.2.5 on 2025-08-31 16:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailotp_user_alter_emailotp_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="expires_at",
            field=models.DateTimeField(default=accounts.models.otp_expiry_time),
        ),
    ]
