# Generated by Django 5.2.5 on 2025-09-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendinguser",
            name="mobile_no",
        ),
    ]
