# Generated by Django 5.2.5 on 2025-09-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_pendinguser_mobile_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="pendinguser",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Optional profile picture for pending users.",
                null=True,
                upload_to="pending_profile_pics/",
            ),
        ),
    ]
