# Generated by Django 5.2.5 on 2025-09-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_pendinguser_mobile_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendinguser",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
