# Generated by Django 5.2.5 on 2025-09-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_pendinguser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Optional profile picture for the user.",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
