# Generated by Django 5.2.5 on 2025-09-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_pendinguser_mobile_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendinguser",
            name="mobile_no",
        ),
    ]
