# Generated by Django 5.2.5 on 2025-09-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_pendinguser_mobile_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendinguser",
            name="address",
        ),
        migrations.RemoveField(
            model_name="pendinguser",
            name="pin_code",
        ),
        migrations.AddField(
            model_name="pendinguser",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="pendinguser",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="pending_profiles/"
            ),
        ),
        migrations.AlterField(
            model_name="pendinguser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="pendinguser",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
