# Generated by Django 5.2.5 on 2025-09-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_pendinguser_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pendinguser",
            options={"verbose_name_plural": "Pending Users"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="profile_pics/"
            ),
        ),
        migrations.AlterField(
            model_name="pendinguser",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
