# Generated by Django 5.2.5 on 2025-09-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="category",
            name="button",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category",
        ),
        migrations.RemoveField(
            model_name="category",
            name="discount_text",
        ),
        migrations.RemoveField(
            model_name="category",
            name="title",
        ),
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default="General", max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="general", max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description for the category", null=True
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for this category",
                null=True,
                upload_to="categories/",
            ),
        ),
    ]
