# Generated by Django 5.2.5 on 2025-09-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_remove_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description for the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image for this category",
                null=True,
                upload_to="categories/",
            ),
        ),
    ]
