# Generated by Django 5.2.5 on 2025-09-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_category_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
