# Generated by Django 5.2.5 on 2025-09-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_alter_category_options_remove_category_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="images",
        ),
    ]
