# Generated by Django 5.2.5 on 2025-09-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banner", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="firstbanner",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "First Banner",
                "verbose_name_plural": "First Banners",
            },
        ),
        migrations.AlterModelOptions(
            name="secondbanner",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Second Banner",
                "verbose_name_plural": "Second Banners",
            },
        ),
        migrations.AddField(
            model_name="firstbanner",
            name="image_description",
            field=models.TextField(
                blank=True,
                help_text="Optional: Provide a short description or alt text for accessibility.",
                null=True,
                verbose_name="Image Description",
            ),
        ),
        migrations.AddField(
            model_name="secondbanner",
            name="image_description",
            field=models.TextField(
                blank=True,
                help_text="Optional: Provide a short description or alt text for accessibility.",
                null=True,
                verbose_name="Image Description",
            ),
        ),
        migrations.AlterField(
            model_name="firstbanner",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="firstbanner",
            name="image",
            field=models.ImageField(
                help_text="Upload an image for the first banner.",
                upload_to="banners/first/",
                verbose_name="Banner Image",
            ),
        ),
        migrations.AlterField(
            model_name="firstbanner",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this banner on the site.",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="firstbanner",
            name="link_url",
            field=models.URLField(
                blank=True,
                help_text="Optional: Add a URL to navigate when clicking the banner.",
                null=True,
                verbose_name="Link URL",
            ),
        ),
        migrations.AlterField(
            model_name="firstbanner",
            name="title",
            field=models.CharField(
                help_text="Enter a catchy title for the first banner.",
                max_length=200,
                verbose_name="Banner Title",
            ),
        ),
        migrations.AlterField(
            model_name="secondbanner",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="secondbanner",
            name="image",
            field=models.ImageField(
                help_text="Upload an image for the second banner.",
                upload_to="banners/second/",
                verbose_name="Banner Image",
            ),
        ),
        migrations.AlterField(
            model_name="secondbanner",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this banner on the site.",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="secondbanner",
            name="link_url",
            field=models.URLField(
                blank=True,
                help_text="Optional: Add a URL to navigate when clicking the banner.",
                null=True,
                verbose_name="Link URL",
            ),
        ),
        migrations.AlterField(
            model_name="secondbanner",
            name="title",
            field=models.CharField(
                help_text="Enter a catchy title for the second banner.",
                max_length=200,
                verbose_name="Banner Title",
            ),
        ),
    ]
