# Generated by Django 5.2.5 on 2025-09-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "banner",
            "0002_alter_firstbanner_options_alter_secondbanner_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FastBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="banners/fast/")),
                ("button_text", models.CharField(blank=True, max_length=50, null=True)),
                ("button_url", models.URLField(blank=True, null=True)),
                (
                    "discount_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fast Banner",
                "verbose_name_plural": "Fast Banners",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="FirstBanner",
        ),
        migrations.RemoveField(
            model_name="secondbanner",
            name="image_description",
        ),
        migrations.RemoveField(
            model_name="secondbanner",
            name="link_url",
        ),
        migrations.AddField(
            model_name="secondbanner",
            name="button_text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="secondbanner",
            name="button_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secondbanner",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="secondbanner",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secondbanner",
            name="discount_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="secondbanner",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="secondbanner",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="secondbanner",
            name="image",
            field=models.ImageField(upload_to="banners/second/"),
        ),
        migrations.AlterField(
            model_name="secondbanner",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="secondbanner",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
