# Generated by Django 5.2.5 on 2025-09-26 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banner", "0003_fastbanner_delete_firstbanner_and_more"),
        ("category", "0002_alter_category_options_remove_category_button_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fastbanner",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fast_banners",
                to="category.category",
            ),
        ),
        migrations.AlterField(
            model_name="secondbanner",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="second_banners",
                to="category.category",
            ),
        ),
    ]
