# Generated by Django 5.2.5 on 2025-09-12 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0003_category_description_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional discounted price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "colors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of colors, e.g. ['black', 'yellow', 'gray']",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "is_new",
                    models.BooleanField(default=False, help_text="Mark as new product"),
                ),
                (
                    "rating",
                    models.FloatField(default=0.0, help_text="Average rating out of 5"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Select category for this product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="category.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
    ]
