# Generated by Django 5.2.5 on 2025-09-12 06:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_category_description_category_image"),
        ("products", "0003_alter_product_colors_alter_product_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Select the category for this product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="category.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Available colors, e.g. ['black', 'yellow', 'gray']",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="Date of creation"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Main product image",
                null=True,
                upload_to="products/",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True, help_text="Toggle availability"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, help_text="Mark as a new product"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Product name", max_length=150, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Base price", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(
                default=0.0,
                help_text="Average rating (0 to 5)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                help_text="SEO-friendly URL slug, auto-generated if blank",
                max_length=180,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Available stock quantity",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Date of last update"),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Optional review comment", null=True
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="Date of creation"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                help_text="Rating from 1 to 5 stars",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                help_text="User who wrote the review",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["name", "slug"], name="products_pr_name_49020f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "user"], name="products_re_product_d30af5_idx"
            ),
        ),
    ]
