# Generated by Django 5.2.5 on 2025-09-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_review_options_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Delivery charge for this product (default 50, can be changed)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="free_delivery_from",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Minimum order amount for free delivery (0 = no free delivery)",
                max_digits=10,
            ),
        ),
    ]
