# Generated by Django 5.2.5 on 2025-09-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_delivery_charge_product_free_delivery_from"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="free_delivery_from",
        ),
        migrations.AddField(
            model_name="product",
            name="free_delivery",
            field=models.BooleanField(
                default=False,
                help_text="If checked, delivery is free and delivery charge is ignored",
            ),
        ),
    ]
