# Generated by Django 5.2.5 on 2025-09-16 17:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_free_delivery_from_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="colors",
            field=models.JSONField(
                blank=True, default=list, help_text="Available colors"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="Date created"),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Delivery charge",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, help_text="Product description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="free_delivery",
            field=models.BooleanField(default=False, help_text="Free delivery?"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Product image", null=True, upload_to="products/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True, help_text="Available for sale?"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, help_text="Mark as new product"),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(
                default=0.0,
                help_text="Average rating",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="Auto-generated slug", max_length=180, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Available stock",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="Last updated"),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, help_text="Review comment", null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="Date created"),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                help_text="Reviewed product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                help_text="Rating (1–5)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                help_text="Reviewer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
